var config = {
    style: "mapbox://styles/ajjerusalem/cl24nlobw000814l9tugz44w9",
    accessToken: "pk.eyJ1IjoiYWpqZXJ1c2FsZW0iLCJhIjoiY2l4b2t3N2lyMDAxMzJxcHMwZ3IzOWN1OSJ9.cxZW0ZgGPFDZpc_-JtRBxg",
    showMarkers: false,
    markerColor: "#3FB1CE",
    // projection: "equirectangular",
    //Read more about available projections here
    //https://docs.mapbox.com/mapbox-gl-js/example/projections/
    inset: false,
    theme: "dark",
    use3dTerrain: true, //set true for enabling 3D maps.
    title: "Let's visit Qatar 2022",
    subtitle: "An immersive tour of the 2022 Football World Cup host nation",
    byline: "By AJLabs",
    footer: "By AJLabs",
    chapters: [
        {
            id: "identifier-1",
            alignment: "center",
            hidden: false,
            title: "FIFA World Cup 2022",
            image: "./gfx/photos/worldcup_2022.jpeg",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.21268, 25.58359],
                zoom: 7.57,
                pitch: 6.5,
                bearing: 0.0,
            },
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [
                // {
                //     layer: "layer-name",
                //     opacity: 1,
                //     duration: 5000,
                // },
            ],
            onChapterExit: [
                // {
                //     layer: 'layer-name',
                //     opacity: 0
                // }
            ],
        },
        // {
        //     id: "identifier-2",
        //     alignment: "center",
        //     hidden: false,
        //     title: "Qatar",
        //     image: "./gfx/photos/official_visit.jpeg",
        //     description:
        //         "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        //     location: {
        //         center: [51.21268, 25.58359],
        //         zoom: 7.57,
        //         pitch: 6.5,
        //         bearing: 0.0,
        //         // flyTo additional controls-
        //         // These options control the flight curve, making it move
        //         // slowly and zoom out almost completely before starting
        //         // to pan.
        //         //speed: 2, // make the flying slow
        //         //curve: 1, // change the speed at which it zooms out
        //     },
        //     mapAnimation: "flyTo",
        //     rotateAnimation: false,
        //     callback: "",
        //     onChapterEnter: [],
        //     onChapterExit: [],
        // },
        {
            id: "identifier-3",
            alignment: "center",
            hidden: false,
            title: "Doha",
            image: "./gfx/photos/doha_skyline_in_the_morning.jpeg",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.51872, 25.28922],
                zoom: 10.96,
                pitch: 58.0,
                bearing: -7.97,
                // flyTo additional controls-
                // These options control the flight curve, making it move
                // slowly and zoom out almost completely before starting
                // to pan.
                //speed: 2, // make the flying slow
                //curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Welcome
        {
            id: "sep-1",
            alignment: "cover",
            hidden: false,
            title: "Welcome to Qatar",
            image: "./gfx/photos/Welcome to Qatar.png",
            description: " ",
            location: {},
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Welcome
        {
            id: "identifier-4",
            alignment: "center",
            hidden: false,
            title: "Hamad International Airport",
            image: "./gfx/photos/hamad_airport_2.jpg",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.61002, 25.26375],
                zoom: 14.29,
                pitch: 58.0,
                bearing: -7.97,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-5",
            alignment: "center",
            hidden: false,
            title: "Top 10 places to visit in Qatar",
            image: "./gfx/photos/Top 10 places to visit in Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.19206, 25.26011],
                zoom: 8.53,
                pitch: 53.0,
                bearing: -0.08,
            },
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-6",
            alignment: "center",
            hidden: false,
            title: "How to travel around Doha",
            image: "./gfx/photos/How to travel around Doha.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.48242, 25.24762],
                zoom: 10.99,
                pitch: 53.0,
                bearing: -0.08,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-7",
            alignment: "center",
            hidden: false,
            title: "Doha metro",
            image: "./gfx/photos/Doha metro.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.52721, 25.28266],
                zoom: 12.85,
                pitch: 53.0,
                bearing: -0.08,
            },
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-7b",
            alignment: "center",
            hidden: false,
            title: " Weather in Qatar",
            image: "./gfx/photos/Weather in Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Shopping
        {
            id: "sep-2",
            alignment: "cover",
            hidden: false,
            title: "Let's go shopping",
            image: "./gfx/photos/Let's go shopping.png",
            description: " ",
            location: {},
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Shopping
        {
            id: "identifier-8",
            alignment: "center",
            hidden: false,
            title: "Let’s visit the Souq",
            image: "./gfx/photos/Souq_Waqif,_Doha,_Catar,_2013-08-05,_DD_92.jpeg",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.53318, 25.28719],
                zoom: 16.0,
                pitch: 53.0,
                bearing: -0.08,
            },
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-9",
            alignment: "center",
            hidden: false,
            title: "Best things to do in Souq Waqif",
            image: "./gfx/photos/Best things to do in Souq Waqif.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.53253, 25.2872],
                zoom: 17.05,
                pitch: 41.0,
                bearing: -0.31,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-10",
            alignment: "fully",
            hidden: false,
            title: "Popular Arabic sayings",
            image: "./gfx/photos/Popular Arabic sayings.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.53253, 25.28784],
                zoom: 17.19,
                pitch: 23.5,
                bearing: 0.0,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-11",
            alignment: "fully",
            hidden: false,
            title: "Malls around Qatar",
            image: "./gfx/photos/Malls around Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.53058, 25.3249],
                zoom: 16.93,
                pitch: 44.5,
                bearing: 0.54,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Welcome
        {
            id: "sep-3",
            alignment: "cover",
            hidden: false,
            title: "Let's know history and culture",
            image: "./gfx/photos/Let's know history and culture.png",
            description: " ",
            location: {},
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Welcome
        {
            id: "identifier-12",
            alignment: "center",
            hidden: false,
            title: "Famous museums in Qatar",
            image: "./gfx/photos/Famous museums in Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.53941, 25.29537],
                zoom: 18.11,
                pitch: 44.5,
                bearing: 0.54,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-13",
            alignment: "center",
            hidden: false,
            title: "Famous mosques in Qatar",
            image: "./gfx/photos/Famous mosques in Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.50655326288099, 25.31735763316052],
                zoom: 17,
                pitch: 44.5,
                bearing: 0.54,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-17",
            alignment: "center",
            hidden: false,
            title: "A brief history of Qatar",
            image: "./gfx/photos/A brief history of Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.14134, 25.06918],
                zoom: 8.82,
                pitch: 44.0,
                bearing: -0.01,
            },
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        // ------------------------------------------------------------------------------------------------------------------ Football
        {
            id: "sep-4",
            alignment: "cover",
            hidden: false,
            title: "Let's breath some air",
            image: "./gfx/photos/Let's breath some air.png",
            description: " ",
            location: {},
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Football
        {
            id: "identifier-14",
            alignment: "center",
            hidden: false,
            title: "Parks around Qatar",
            image: "./gfx/photos/Parks around Qatar.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.54749, 25.29056],
                zoom: 17.31,
                pitch: 44.5,
                bearing: 0.54,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-15",
            alignment: "center",
            hidden: false,
            title: "Let’s explore the Pearl",
            image: "./gfx/photos/pearl_qatar.jpeg",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.5544, 25.36878],
                zoom: 13.72,
                pitch: 60.0,
                bearing: -0.04,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        {
            id: "identifier-16",
            alignment: "center",
            hidden: false,
            title: "Let’s visit the desert",
            image: "./gfx/photos/Let’s visit the desert.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.3405, 24.58061],
                zoom: 14.57,
                pitch: 60.0,
                bearing: -0.0,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Football
        {
            id: "sep-5",
            alignment: "cover",
            hidden: false,
            title: "Let's play football",
            image: "./gfx/photos/Let's play football.png",
            description: " ",
            location: {},
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
        // ------------------------------------------------------------------------------------------------------------------ Football
        {
            id: "identifier-18",
            alignment: "center",
            hidden: false,
            title: "World Cup 2022 Stadiums",
            image: "./gfx/photos/FIFA World Cup 2022 Stadiums.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.17165, 25.29945],
                zoom: 8.14,
                pitch: 0.0,
                bearing: 0.61,
            },
            mapAnimation: "flyTo",
            rotateAnimation: false,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-19",
            alignment: "center",
            hidden: false,
            title: "Al Bayt Stadium",
            image: "./gfx/photos/Al Bayt Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.48609, 25.6526],
                zoom: 15.85,
                pitch: 42.5,
                bearing: 87.81,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-20",
            alignment: "center",
            hidden: false,
            title: "Lusail Stadium",
            image: "./gfx/photos/Lusail Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.49037, 25.42077],
                zoom: 16.9,
                pitch: 44.5,
                bearing: 0.0,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-21",
            alignment: "center",
            hidden: false,
            title: "Education City Stadium",
            image: "./gfx/photos/Education City Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.42441, 25.31084],
                zoom: 16.9,
                pitch: 44.5,
                bearing: 0.0,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-22",
            alignment: "center",
            hidden: false,
            title: "Khalifa International Stadium",
            image: "./gfx/photos/Khalifa International Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.44813, 25.26372],
                zoom: 16.7,
                pitch: 44.5,
                bearing: 0.0,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-23",
            alignment: "center",
            hidden: false,
            title: "Ahmed Bin Ali Stadium",
            image: "./gfx/photos/Ahmed Bin Ali Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.342315830188014, 25.329776675167786],
                zoom: 17,
                pitch: 60.0,
                bearing: 151.2,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-24",
            alignment: "center",
            hidden: false,
            title: "Stadium 974",
            image: "./gfx/photos/Stadium 974.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.56631264643708, 25.28916457293318],
                zoom: 17,
                pitch: 60.0,
                bearing: 12.8,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-25",
            alignment: "center",
            hidden: false,
            title: "Al Thumama Stadium",
            image: "./gfx/photos/Al Thumama Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.53242017549998, 25.23535352420109],
                zoom: 17,
                pitch: 60.0,
                bearing: 151.2,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },

        {
            id: "identifier-26",
            alignment: "center",
            hidden: false,
            title: "Al Janoub Stadium",
            image: "./gfx/photos/Al Janoub Stadium.png",
            description:
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            location: {
                center: [51.57420058232935, 25.160011203829534],
                zoom: 17,
                pitch: 60.0,
                bearing: 151.2,
            },
            mapAnimation: "flyTo",
            rotateAnimation: true,
            callback: "",
            onChapterEnter: [],
            onChapterExit: [],
        },
    ],
};
